### ISSUE TITLE
Windows installers TODO

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver#77]
Work that needs doing before the windows installers can be pushed.

- [ ] find out why thelonious "file" key storage option (still) does not seem to work.
- [ ] find out if there are other compatibility issues.
- [ ] add any necessary patches.
- [x] do the big repo sync and updates to master branches.
- [ ] write the installer script.

**Comment by androlo** [comment]
- [ ] see how docker affects this

**Comment by androlo** [comment]
docker first. re-opening if this becomes important again.
